[package]
name = "cari"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
clap = { version = "4.6.6", features = ["derive"] }
color-eyre = "0.6.5"
futures = "0.3.33"
futures-util = "0.3.33"
heck = "0.5.0"
hex = "0.4.3"
open = "5.4.1"
reqwest = { version = "0.13.4", features = ["json", "query", "stream"] }
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
tokio = { version = "1.53.1", features = ["full"] }
trash = "5.2.6"
yansi = "1.0.1"
