[package]
name = "cari"
version = "0.4.0"
edition = "2024"
license = "MIT"
description = "Simple package manager for minecraft servers"
repository = "https://github.com/ghostdevv/cari"
include = ["src/**/*", "LICENSE", "README.md"]

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
clap = { version = "4.6.6", features = ["derive"] }
color-eyre = "0.6.5"
futures = "0.3.34"
futures-util = "0.3.34"
heck = "0.5.0"
hex = "0.4.3"
ignore = "0.4.33"
indicatif = "0.18.6"
open = "5.4.3"
reqwest = { version = "0.13.4", features = ["json", "query", "stream"] }
schemars = { version = "1.2.2", optional = true }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
sha2 = "0.11.0"
strum = "0.28.0"
strum_macros = "0.28.0"
tokio = { version = "1.53.1", features = ["full"] }
trash = "5.2.6"
yansi = "1.0.1"

[features]
schema = ["dep:schemars"]

[profile.release]
opt-level = 3
debug = false
strip = "symbols"
lto = "fat"
panic = "abort"
codegen-units = 1

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
